apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
  labels:
    app: mysql
    project: expense
    tier: database
spec:
  clusterIP: None
  selector:
    app: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  serviceName: mysql-headless
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: mysql
      project: expense
      tier: db
  template:
    metadata:
      labels:
        app: mysql
        project: expense
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: pothugunta/mysql:1.0.0
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: expense-ebs-sc
      resources:
        requests:
          storage: 1Gi